version: '3'
name: 'companions'
services:
  client:
    container_name: client
    env_file: ./apps/client/.env.local
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 3000:3000

  api:
    container_name: api
    env_file: ./apps/api/.env
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 2703:2703
