import { poppins, ptSerif } from './lib/config/font';
import './styles/global.scss';
import type { Metadata } from 'next';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${ptSerif.variable}`}>
        {children}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};
